In [1]:
#
# Quelle: http://juddzone.com/ALGORITHMS/least_squares_3D_ellipsoid.html
#

import numpy as np
from numpy.linalg import eig, inv

# Hier kommen erstmal ewig viele Zeilen an Engabedaten. Bitte ganz nach unten wechseln!

xx = np.array([272.0, 281.0, 281.0, 286.0, 286.0, 290.0, 295.0, 298.0, 296.0, 306.0,
304.0, 305.0, 304.0, 299.0, 290.0, 276.0, 258.0, 241.0, 213.0, 191.0,
169.0, 147.0, 131.0, 113.0, 101.0, 81.0, 70.0, 58.0, 51.0, 42.0, 32.0,
7.0, 21.0, -20.0, -41.0, -20.0, -67.0, -93.0, -120.0, -146.0, -172.0,
-196.0, -233.0, -245.0, -265.0, -272.0, -284.0, -283.0, -284.0, -279.0,
-272.0, -267.0, -259.0, -256.0, -250.0, -244.0, -241.0, -238.0, -231.0,
-219.0, -208.0, -208.0, -204.0, -198.0, -185.0, -178.0, -167.0, -156.0,
-143.0, -123.0, -92.0, -54.0, -18.0, 15.0, 47.0, 101.0, 101.0, 125.0,
149.0, 166.0, 192.0, 208.0, 222.0, 242.0, 250.0, 246.0, 246.0, 240.0,
235.0, 232.0, 225.0, 220.0, 221.0, 217.0, 212.0, 207.0, 197.0, 194.0,
182.0, 176.0, 173.0, 168.0, 160.0, 154.0, 152.0, 141.0, 141.0, 142.0,
152.0, 155.0, 170.0, 183.0, 201.0, 226.0, 239.0, 257.0, 275.0, 289.0,
298.0, 292.0, 285.0, 262.0, 224.0, 188.0, 104.0, 65.0, 27.0, 0.0, -31.0,
-64.0, -93.0, -93.0, -136.0, -155.0, -173.0, -187.0, -197.0, -197.0,
-200.0, -207.0, -202.0, -202.0, -202.0, -196.0, -189.0, -195.0, -178.0,
-178.0, -166.0, -95.0, -95.0, -62.0, -29.0, -1.0, 26.0, 42.0, 62.0,
75.0, 90.0, 101.0, 108.0, 119.0, 118.0, 111.0, 107.0, 101.0, 99.0, 99.0,
96.0, 80.0, 90.0, 65.0, 54.0, 45.0, 31.0, 22.0, 4.0, -4.0, -14.0, -18.0,
-21.0, -20.0, -21.0, -23.0, -8.0, -8.0, -1.0, 9.0, 13.0, 20.0, 29.0,
26.0, 27.0, 26.0, 29.0, 26.0, 32.0, 33.0, 33.0, 32.0, 31.0, 26.0, 17.0,
8.0, -12.0, -23.0, -69.0, -93.0, -117.0, -117.0, -165.0, -184.0, -206.0,
-217.0, -229.0, -236.0, -250.0, -257.0, -262.0, -265.0, -278.0, -284.0,
-286.0, -296.0, -300.0, -301.0, -302.0, -302.0, -303.0, -306.0, -305.0,
-309.0, -308.0, -307.0, -309.0, -308.0, -304.0, -310.0, -308.0, -302.0,
-299.0, -295.0, -295.0, -302.0, -303.0, -308.0, -316.0, -327.0, -337.0,
-338.0, -340.0, -335.0, -333.0, -327.0, -316.0, -303.0, -291.0, -275.0,
-253.0, -233.0, -207.0, -174.0, -140.0, -108.0, -81.0, -38.0, -23.0,
-38.0, -12.0, -3.0, 0.0, 4.0, 3.0, -1.0, 0.0, -2.0, -5.0, -13.0, -21.0,
-30.0, -42.0, -61.0, -76.0, -86.0, -89.0, -92.0, -92.0, -89.0, -74.0,
-65.0, -48.0, -32.0, -14.0, -2.0, 6.0, 12.0, 27.0, 18.0, 27.0, 44.0,
92.0, 110.0, 114.0, 118.0, 122.0, 123.0, 117.0, 112.0, 112.0, 106.0,
106.0, 117.0, 117.0, 119.0, 117.0, 121.0, 116.0, 116.0, 111.0, 112.0,
122.0, 136.0, 148.0, 160.0, 178.0, 198.0, 219.0, 241.0, 253.0, 272.0,
285.0, 292.0, 297.0, 291.0, 291.0, 287.0, 273.0, 260.0, 247.0, 223.0,
195.0, 162.0, 127.0, 94.0, 58.0, 20.0, -12.0, -47.0, -47.0, -113.0,
-142.0, -168.0, -192.0, -217.0, -233.0, -251.0, -262.0, -272.0, -277.0,
-283.0, -281.0, -282.0, -279.0, -274.0, -259.0, -237.0, -216.0, -195.0,
-177.0, -167.0, -154.0, -146.0, -142.0, -138.0, -126.0, -120.0, -107.0,
-87.0, -59.0, -27.0, 8.0, 41.0, 60.0, 81.0, 86.0, 97.0, 116.0, 109.0,
128.0, 147.0, 147.0, 163.0, 175.0, 187.0, 196.0, 199.0, 215.0, 226.0,
235.0, 243.0, 245.0, 247.0, 237.0, 222.0, 208.0, 184.0, 160.0, 123.0,
87.0, 47.0, -44.0, -44.0, -97.0, -136.0, -168.0, -202.0, -240.0, -252.0,
-255.0, -263.0, -273.0, -286.0, -289.0, -295.0, -308.0, -310.0, -308.0,
-307.0, -313.0, -311.0, -315.0, -310.0, -309.0, -304.0, -300.0, -295.0,
-281.0, -281.0, -271.0, -269.0, -264.0, -264.0, -259.0, -256.0, -257.0,
-257.0, -281.0, -281.0, -280.0, -284.0, -279.0, -270.0, -260.0, -253.0,
-232.0, -211.0, -191.0, -168.0, -118.0, -96.0, -73.0, -61.0, -44.0,
-34.0, -29.0, -20.0, -21.0, -19.0, -13.0, -14.0, -16.0, -14.0, -5.0,
1.0, 15.0, 27.0, 37.0, 45.0, 52.0, 55.0, 56.0, 64.0, 76.0, 95.0, 116.0,
165.0, 137.0, 191.0, 191.0, 249.0, 275.0, 293.0, 298.0, 295.0, 279.0,
255.0, 224.0, 193.0, 157.0, 128.0, 87.0, 80.0, 85.0, 87.0, 79.0, 71.0,
70.0, 63.0, 56.0, 41.0, 33.0, 33.0, 45.0, 43.0, 80.0, 96.0, 80.0, 121.0,
146.0, 167.0, 184.0, 197.0, 216.0, 232.0, 242.0, 248.0, 251.0, 257.0,
258.0, 256.0, 255.0, 245.0, 245.0, 237.0, 226.0, 208.0, 185.0, 156.0,
125.0, 104.0, 88.0, 100.0, 119.0, 120.0, 112.0, 105.0, 100.0, 82.0,
68.0, 55.0, 35.0, 27.0, 22.0, 22.0, 20.0, 23.0, 25.0, 30.0, 35.0, 28.0,
38.0, 38.0, 50.0, 53.0, 57.0, 51.0, 44.0, 35.0, 28.0, 18.0, 16.0, 22.0,
24.0, 29.0, 42.0, 52.0, 62.0, 71.0, 82.0, 80.0, 85.0, 95.0, 114.0,
123.0, 132.0, 144.0, 146.0, 139.0, 128.0, 106.0, 81.0, 53.0, 22.0,
-11.0, -70.0, -70.0, -95.0, -124.0, -148.0, -173.0, -195.0, -217.0,
-235.0, -251.0, -265.0, -279.0, -290.0, -299.0, -303.0, -305.0, -311.0,
-313.0, -311.0, -312.0, -309.0, -305.0, -307.0, -305.0, -299.0, -296.0,
-284.0, -284.0, -277.0, -271.0, -271.0, -228.0, -215.0, -196.0, -168.0,
-136.0, -99.0, -66.0, -20.0, 21.0, 62.0, 94.0, 119.0, 145.0, 167.0,
175.0, 194.0, 203.0, 232.0, 247.0, 232.0, 261.0, 265.0, 275.0, 280.0,
282.0, 289.0, 295.0, 295.0, 290.0, 278.0, 256.0, 234.0, 215.0, 198.0,
183.0, 156.0, 130.0, 94.0, 65.0, 38.0, 10.0, -62.0, -17.0, -102.0,
-123.0, -102.0, -145.0, -171.0, -193.0, -212.0, -231.0, -247.0, -266.0,
-280.0, -289.0, -298.0, -308.0, -313.0, -310.0, -314.0, -309.0, -308.0,
-307.0, -299.0, -294.0, -287.0, -279.0, -268.0, -256.0, -246.0, -235.0,
-220.0, -208.0, -172.0, -191.0, -172.0, -129.0, -99.0, -70.0, -50.0,
-28.0, -10.0, 5.0, 22.0, 70.0, 97.0, 120.0, 147.0, 174.0, 199.0, 220.0,
231.0, 238.0, 249.0, 257.0, 267.0, 289.0, 289.0, 297.0, 292.0, 291.0,
268.0, 248.0, 217.0, 177.0, 134.0, 86.0, 30.0, -23.0, -69.0, -106.0,
-136.0, -156.0, -177.0, -188.0, -199.0, -210.0, -225.0, -225.0, -225.0,
-258.0, -258.0, -271.0, -276.0, -283.0, -290.0, -300.0, -305.0, -311.0,
-317.0, -322.0, -322.0, -320.0, -317.0, -308.0, -294.0, -279.0, -264.0,
-254.0, -243.0, -232.0, -216.0, -198.0, -179.0, -162.0, -162.0, -109.0,
-91.0, -78.0, -70.0, -61.0, -55.0, -53.0, -52.0, -52.0, -59.0, -69.0,
-74.0, -81.0, -91.0, -103.0, -112.0, -114.0, -122.0, -128.0, -136.0,
-138.0, -145.0, -144.0, -142.0, -139.0, -133.0, -134.0, -131.0, -121.0,
-127.0, -115.0, -115.0, -78.0, -62.0, -62.0, -47.0, -25.0, -4.0, 11.0,
24.0, 45.0, 81.0, 111.0, 143.0, 155.0, 177.0, 196.0, 204.0, 214.0,
240.0, 227.0, 265.0, 265.0, 265.0, 283.0, 287.0, 287.0, 297.0, 293.0,
292.0, 290.0, 284.0, 281.0, 268.0, 250.0, 229.0, 217.0, 201.0, 201.0,
184.0, 172.0, 160.0, 154.0, 158.0, 162.0, 157.0, 154.0, 149.0, 147.0,
142.0, 138.0, 135.0, 126.0, 117.0, 103.0, 103.0, 78.0, 63.0, 52.0, 44.0,
31.0, 14.0, 5.0, 1.0, 1.0, 0.0, -4.0, 1.0, 14.0, 32.0, 43.0, 57.0, 66.0,
75.0, 83.0, 94.0, 102.0, 111.0, 127.0, 138.0, 149.0, 151.0, 155.0,
152.0, 150.0, 144.0, 137.0, 129.0, 123.0, 115.0, 97.0, 100.0, 92.0,
96.0, 92.0, 92.0, 98.0, 106.0, 113.0, 132.0, 154.0, 177.0, 198.0, 221.0,
237.0, 257.0, 273.0, 293.0, 289.0, 283.0, 286.0, 284.0, 284.0, 280.0,
271.0, 255.0, 240.0, 213.0, 176.0, 122.0, 122.0, -137.0, -208.0, -269.0,
-310.0, -337.0, -351.0, -343.0, -333.0, -311.0, -294.0, -242.0, -242.0,
-224.0, -208.0, -201.0, -193.0, -182.0, -176.0, -165.0, -148.0, -136.0,
-100.0, -100.0, -57.0, -57.0, -18.0, -33.0, 4.0, 18.0, 38.0, 54.0, 74.0,
97.0, 97.0, 128.0, 143.0, 143.0, 172.0, 172.0, 211.0, 223.0, 229.0,
242.0, 241.0, 245.0, 240.0, 242.0, 238.0, 235.0, 235.0, 236.0, 235.0,
237.0, 237.0, 248.0, 256.0, 267.0, 273.0, 279.0, 280.0, 289.0, 285.0,
275.0, 256.0, 226.0, 184.0, 138.0, 84.0, 37.0, -2.0, -2.0, -94.0,
-133.0, -163.0, -200.0, -239.0])
yy = np.array([-1783.0, -1784.0,
-1784.0, -1780.0, -1780.0, -1781.0, -1779.0, -1784.0, -1790.0, -1798.0,
-1814.0, -1829.0, -1852.0, -1880.0, -1899.0, -1916.0, -1945.0, -1960.0,
-1981.0, -1997.0, -2010.0, -2024.0, -2034.0, -2043.0, -2060.0, -2073.0,
-2083.0, -2093.0, -2100.0, -2108.0, -2116.0, -2125.0, -2125.0, -2133.0,
-2134.0, -2133.0, -2128.0, -2123.0, -2113.0, -2102.0, -2094.0, -2075.0,
-2045.0, -2020.0, -2001.0, -1983.0, -1966.0, -1945.0, -1929.0, -1913.0,
-1892.0, -1885.0, -1867.0, -1855.0, -1843.0, -1837.0, -1832.0, -1825.0,
-1817.0, -1813.0, -1810.0, -1810.0, -1817.0, -1824.0, -1836.0, -1855.0,
-1880.0, -1909.0, -1940.0, -1971.0, -1994.0, -2027.0, -2041.0, -2052.0,
-2060.0, -2071.0, -2071.0, -2073.0, -2068.0, -2063.0, -2056.0, -2041.0,
-2019.0, -1969.0, -1950.0, -1920.0, -1895.0, -1876.0, -1861.0, -1843.0,
-1831.0, -1813.0, -1800.0, -1774.0, -1761.0, -1736.0, -1724.0, -1701.0,
-1688.0, -1671.0, -1669.0, -1660.0, -1656.0, -1650.0, -1645.0, -1639.0,
-1639.0, -1640.0, -1644.0, -1646.0, -1659.0, -1666.0, -1676.0, -1698.0,
-1714.0, -1737.0, -1757.0, -1775.0, -1802.0, -1825.0, -1857.0, -1888.0,
-1914.0, -1944.0, -1991.0, -2018.0, -2035.0, -2059.0, -2065.0, -2076.0,
-2085.0, -2085.0, -2086.0, -2083.0, -2080.0, -2070.0, -2069.0, -2069.0,
-2069.0, -2074.0, -2080.0, -2080.0, -2080.0, -2085.0, -2093.0, -2095.0,
-2104.0, -2104.0, -2111.0, -2120.0, -2120.0, -2120.0, -2113.0, -2105.0,
-2085.0, -2079.0, -2065.0, -2058.0, -2037.0, -2023.0, -1986.0, -1956.0,
-1930.0, -1888.0, -1861.0, -1808.0, -1789.0, -1773.0, -1755.0, -1735.0,
-1734.0, -1718.0, -1703.0, -1698.0, -1682.0, -1672.0, -1659.0, -1642.0,
-1630.0, -1621.0, -1609.0, -1608.0, -1609.0, -1606.0, -1601.0, -1601.0,
-1603.0, -1613.0, -1628.0, -1638.0, -1659.0, -1670.0, -1693.0, -1716.0,
-1750.0, -1782.0, -1807.0, -1835.0, -1872.0, -1901.0, -1930.0, -1956.0,
-1976.0, -1995.0, -2011.0, -2028.0, -2047.0, -2056.0, -2056.0, -2056.0,
-2049.0, -2038.0, -2025.0, -2011.0, -1999.0, -1983.0, -1965.0, -1946.0,
-1919.0, -1902.0, -1880.0, -1859.0, -1844.0, -1831.0, -1817.0, -1801.0,
-1785.0, -1772.0, -1757.0, -1740.0, -1733.0, -1723.0, -1714.0, -1708.0,
-1703.0, -1704.0, -1698.0, -1692.0, -1687.0, -1678.0, -1674.0, -1669.0,
-1669.0, -1672.0, -1675.0, -1686.0, -1705.0, -1722.0, -1770.0, -1799.0,
-1820.0, -1847.0, -1876.0, -1897.0, -1921.0, -1944.0, -1963.0, -1986.0,
-2004.0, -2025.0, -2049.0, -2073.0, -2090.0, -2102.0, -2119.0, -2136.0,
-2141.0, -2136.0, -2138.0, -2136.0, -2135.0, -2136.0, -2122.0, -2108.0,
-2099.0, -2071.0, -2041.0, -2014.0, -1992.0, -1969.0, -1949.0, -1935.0,
-1922.0, -1900.0, -1876.0, -1858.0, -1838.0, -1812.0, -1785.0, -1749.0,
-1709.0, -1694.0, -1684.0, -1678.0, -1671.0, -1671.0, -1669.0, -1668.0,
-1669.0, -1667.0, -1653.0, -1641.0, -1630.0, -1614.0, -1611.0, -1607.0,
-1596.0, -1589.0, -1585.0, -1577.0, -1577.0, -1569.0, -1569.0, -1563.0,
-1563.0, -1556.0, -1552.0, -1552.0, -1551.0, -1554.0, -1557.0, -1561.0,
-1566.0, -1581.0, -1592.0, -1610.0, -1631.0, -1653.0, -1680.0, -1722.0,
-1752.0, -1792.0, -1847.0, -1868.0, -1886.0, -1911.0, -1934.0, -1953.0,
-1984.0, -2010.0, -2037.0, -2062.0, -2086.0, -2103.0, -2122.0, -2129.0,
-2132.0, -2135.0, -2135.0, -2129.0, -2116.0, -2108.0, -2096.0, -2081.0,
-2065.0, -2046.0, -2027.0, -2005.0, -1979.0, -1961.0, -1946.0, -1935.0,
-1926.0, -1908.0, -1899.0, -1885.0, -1869.0, -1852.0, -1843.0, -1829.0,
-1820.0, -1811.0, -1805.0, -1801.0, -1787.0, -1781.0, -1770.0, -1764.0,
-1747.0, -1738.0, -1734.0, -1724.0, -1707.0, -1698.0, -1694.0, -1694.0,
-1690.0, -1688.0, -1683.0, -1685.0, -1685.0, -1694.0, -1700.0, -1715.0,
-1725.0, -1735.0, -1745.0, -1755.0, -1775.0, -1802.0, -1834.0, -1856.0,
-1878.0, -1911.0, -1939.0, -1966.0, -1993.0, -2014.0, -2025.0, -2028.0,
-2033.0, -2033.0, -2029.0, -2025.0, -2017.0, -2000.0, -1980.0, -1973.0,
-1972.0, -1964.0, -1959.0, -1954.0, -1956.0, -1958.0, -1952.0, -1952.0,
-1946.0, -1939.0, -1936.0, -1924.0, -1919.0, -1910.0, -1906.0, -1901.0,
-1893.0, -1883.0, -1881.0, -1881.0, -1898.0, -1914.0, -1920.0, -1920.0,
-1919.0, -1911.0, -1910.0, -1910.0, -1910.0, -1910.0, -1908.0, -1900.0,
-1899.0, -1895.0, -1888.0, -1878.0, -1873.0, -1862.0, -1859.0, -1855.0,
-1851.0, -1851.0, -1843.0, -1839.0, -1833.0, -1824.0, -1807.0, -1801.0,
-1793.0, -1782.0, -1778.0, -1768.0, -1767.0, -1768.0, -1771.0, -1784.0,
-1797.0, -1824.0, -1845.0, -1864.0, -1881.0, -1897.0, -1902.0, -1909.0,
-1919.0, -1921.0, -1926.0, -1922.0, -1928.0, -1928.0, -1928.0, -1911.0,
-1898.0, -1883.0, -1865.0, -1842.0, -1825.0, -1801.0, -1777.0, -1758.0,
-1739.0, -1718.0, -1683.0, -1664.0, -1649.0, -1632.0, -1625.0, -1611.0,
-1603.0, -1596.0, -1584.0, -1577.0, -1571.0, -1570.0, -1573.0, -1568.0,
-1573.0, -1573.0, -1573.0, -1579.0, -1585.0, -1593.0, -1605.0, -1620.0,
-1628.0, -1643.0, -1662.0, -1670.0, -1675.0, -1677.0, -1684.0, -1685.0,
-1685.0, -1681.0, -1681.0, -1677.0, -1673.0, -1664.0, -1659.0, -1653.0,
-1638.0, -1630.0, -1617.0, -1591.0, -1584.0, -1574.0, -1571.0, -1557.0,
-1557.0, -1546.0, -1544.0, -1545.0, -1538.0, -1532.0, -1531.0, -1533.0,
-1525.0, -1525.0, -1524.0, -1524.0, -1524.0, -1521.0, -1524.0, -1524.0,
-1533.0, -1536.0, -1548.0, -1551.0, -1562.0, -1572.0, -1577.0, -1592.0,
-1607.0, -1623.0, -1640.0, -1664.0, -1688.0, -1715.0, -1744.0, -1773.0,
-1802.0, -1825.0, -1858.0, -1880.0, -1939.0, -1965.0, -1996.0, -2013.0,
-2040.0, -2057.0, -2080.0, -2093.0, -2109.0, -2111.0, -2125.0, -2130.0,
-2130.0, -2130.0, -2125.0, -2116.0, -2108.0, -2086.0, -2071.0, -2053.0,
-2033.0, -2014.0, -1995.0, -1976.0, -1960.0, -1937.0, -1922.0, -1906.0,
-1891.0, -1877.0, -1863.0, -1862.0, -1854.0, -1845.0, -1845.0, -1840.0,
-1841.0, -1832.0, -1834.0, -1834.0, -1840.0, -1845.0, -1845.0, -1847.0,
-1846.0, -1845.0, -1845.0, -1839.0, -1832.0, -1825.0, -1814.0, -1806.0,
-1791.0, -1779.0, -1766.0, -1748.0, -1739.0, -1730.0, -1722.0, -1710.0,
-1701.0, -1696.0, -1701.0, -1696.0, -1693.0, -1703.0, -1710.0, -1720.0,
-1737.0, -1764.0, -1789.0, -1821.0, -1852.0, -1884.0, -1908.0, -1933.0,
-1957.0, -1980.0, -2004.0, -2025.0, -2044.0, -2062.0, -2069.0, -2079.0,
-2086.0, -2083.0, -2095.0, -2098.0, -2095.0, -2088.0, -2083.0, -2074.0,
-2061.0, -2041.0, -2028.0, -2007.0, -1986.0, -1968.0, -1942.0, -1909.0,
-1890.0, -1863.0, -1842.0, -1824.0, -1803.0, -1781.0, -1763.0, -1746.0,
-1735.0, -1713.0, -1706.0, -1693.0, -1680.0, -1675.0, -1663.0, -1655.0,
-1653.0, -1649.0, -1653.0, -1660.0, -1669.0, -1685.0, -1702.0, -1708.0,
-1716.0, -1731.0, -1744.0, -1774.0, -1793.0, -1808.0, -1824.0, -1843.0,
-1862.0, -1881.0, -1892.0, -1899.0, -1908.0, -1909.0, -1908.0, -1901.0,
-1901.0, -1890.0, -1882.0, -1869.0, -1856.0, -1841.0, -1827.0, -1816.0,
-1802.0, -1779.0, -1759.0, -1738.0, -1719.0, -1698.0, -1688.0, -1676.0,
-1669.0, -1660.0, -1652.0, -1653.0, -1654.0, -1654.0, -1654.0, -1658.0,
-1658.0, -1660.0, -1669.0, -1677.0, -1687.0, -1714.0, -1729.0, -1748.0,
-1763.0, -1787.0, -1805.0, -1832.0, -1861.0, -1887.0, -1923.0, -1949.0,
-1969.0, -1990.0, -2016.0, -2038.0, -2058.0, -2074.0, -2087.0, -2105.0,
-2105.0, -2110.0, -2109.0, -2096.0, -2081.0, -2067.0, -2051.0, -2031.0,
-2016.0, -1994.0, -1975.0, -1955.0, -1930.0, -1911.0, -1891.0, -1875.0,
-1855.0, -1830.0, -1805.0, -1775.0, -1749.0, -1722.0, -1695.0, -1654.0,
-1637.0, -1623.0, -1612.0, -1604.0, -1588.0, -1576.0, -1576.0, -1570.0,
-1570.0, -1570.0, -1572.0, -1572.0, -1582.0, -1585.0, -1600.0, -1611.0,
-1628.0, -1648.0, -1666.0, -1694.0, -1722.0, -1755.0, -1793.0, -1829.0,
-1863.0, -1895.0, -1907.0, -1910.0, -1901.0, -1901.0, -1901.0, -1897.0,
-1894.0, -1894.0, -1881.0, -1872.0, -1857.0, -1841.0, -1819.0, -1809.0,
-1792.0, -1776.0, -1758.0, -1747.0, -1745.0, -1745.0, -1745.0, -1757.0,
-1759.0, -1786.0, -1816.0, -1842.0, -1874.0, -1909.0, -1933.0, -1968.0,
-1993.0, -2027.0, -2053.0, -2074.0, -2094.0, -2105.0, -2105.0, -2116.0,
-2109.0, -2094.0, -2071.0, -2054.0, -2034.0, -2021.0, -2004.0, -1995.0,
-1981.0, -1961.0, -1950.0, -1927.0, -1911.0, -1892.0, -1872.0, -1855.0,
-1836.0, -1818.0, -1800.0, -1785.0, -1760.0, -1726.0, -1705.0, -1683.0,
-1669.0, -1647.0, -1629.0, -1611.0, -1601.0, -1588.0, -1576.0, -1564.0,
-1561.0, -1557.0, -1554.0, -1556.0, -1551.0, -1549.0, -1549.0, -1551.0,
-1557.0, -1563.0, -1564.0, -1578.0, -1591.0, -1606.0, -1628.0, -1659.0,
-1696.0, -1735.0, -1788.0, -1841.0, -1881.0, -1902.0, -1910.0, -1916.0,
-1935.0, -1946.0, -1948.0, -1964.0, -1969.0, -1987.0, -1992.0, -1992.0,
-1980.0, -1966.0, -1943.0, -1923.0, -1901.0, -1876.0, -1844.0, -1814.0,
-1792.0, -1771.0, -1778.0, -1778.0, -1788.0, -1804.0, -1814.0, -1820.0,
-1832.0, -1844.0, -1854.0, -1862.0, -1878.0, -1888.0, -1888.0, -1885.0,
-1885.0, -1887.0, -1888.0, -1897.0, -1909.0, -1913.0, -1918.0, -1921.0,
-1920.0, -1920.0, -1917.0, -1913.0, -1913.0, -1914.0, -1914.0, -1904.0,
-1894.0, -1884.0, -1852.0, -1845.0, -1827.0, -1814.0, -1798.0, -1786.0,
-1774.0, -1769.0, -1764.0, -1764.0, -1763.0, -1763.0, -1770.0, -1782.0,
-1786.0, -1795.0, -1805.0, -1820.0, -1837.0, -1854.0, -1871.0, -1898.0,
-1919.0, -1951.0, -1977.0, -1997.0, -2013.0, -2028.0, -2028.0, -2030.0,
-2025.0, -2021.0, -2008.0, -1991.0])
zz = np.array([-167.0, -185.0,
-185.0, -207.0, -207.0, -217.0, -227.0, -245.0, -257.0, -267.0, -289.0,
-311.0, -333.0, -354.0, -376.0, -399.0, -422.0, -440.0, -459.0, -475.0,
-484.0, -490.0, -494.0, -492.0, -488.0, -483.0, -472.0, -458.0, -445.0,
-432.0, -420.0, -398.0, -408.0, -384.0, -384.0, -384.0, -385.0, -388.0,
-393.0, -398.0, -403.0, -408.0, -415.0, -422.0, -432.0, -440.0, -452.0,
-461.0, -471.0, -487.0, -496.0, -511.0, -518.0, -529.0, -531.0, -535.0,
-539.0, -545.0, -548.0, -557.0, -564.0, -564.0, -570.0, -573.0, -576.0,
-579.0, -579.0, -577.0, -576.0, -571.0, -561.0, -550.0, -536.0, -515.0,
-496.0, -451.0, -451.0, -425.0, -396.0, -369.0, -341.0, -308.0, -278.0,
-218.0, -193.0, -171.0, -155.0, -139.0, -130.0, -123.0, -116.0, -114.0,
-114.0, -115.0, -114.0, -116.0, -115.0, -116.0, -117.0, -121.0, -123.0,
-124.0, -122.0, -118.0, -117.0, -118.0, -118.0, -115.0, -115.0, -117.0,
-126.0, -133.0, -146.0, -162.0, -178.0, -201.0, -230.0, -268.0, -307.0,
-353.0, -395.0, -441.0, -477.0, -512.0, -541.0, -542.0, -533.0, -520.0,
-504.0, -483.0, -465.0, -465.0, -433.0, -424.0, -418.0, -413.0, -412.0,
-412.0, -402.0, -395.0, -368.0, -368.0, -368.0, -351.0, -325.0, -338.0,
-310.0, -310.0, -293.0, -227.0, -227.0, -204.0, -185.0, -164.0, -149.0,
-133.0, -125.0, -114.0, -103.0, -92.0, -74.0, -57.0, -45.0, -33.0,
-27.0, -25.0, -27.0, -33.0, -32.0, -36.0, -36.0, -36.0, -37.0, -39.0,
-41.0, -48.0, -55.0, -66.0, -75.0, -83.0, -95.0, -89.0, -95.0, -97.0,
-99.0, -99.0, -93.0, -88.0, -79.0, -68.0, -56.0, -43.0, -28.0, -20.0,
-12.0, -2.0, -3.0, -4.0, -6.0, -10.0, -19.0, -32.0, -39.0, -48.0, -58.0,
-67.0, -95.0, -105.0, -118.0, -118.0, -133.0, -137.0, -135.0, -133.0,
-129.0, -129.0, -128.0, -123.0, -118.0, -117.0, -117.0, -121.0, -125.0,
-133.0, -141.0, -150.0, -156.0, -164.0, -173.0, -183.0, -193.0, -204.0,
-213.0, -223.0, -242.0, -228.0, -253.0, -263.0, -275.0, -282.0, -290.0,
-299.0, -299.0, -301.0, -306.0, -311.0, -316.0, -323.0, -351.0, -360.0,
-367.0, -377.0, -384.0, -393.0, -410.0, -421.0, -433.0, -439.0, -444.0,
-455.0, -457.0, -455.0, -440.0, -433.0, -416.0, -377.0, -354.0, -377.0,
-329.0, -299.0, -271.0, -241.0, -211.0, -175.0, -143.0, -109.0, -78.0,
-56.0, -40.0, -27.0, -20.0, -12.0, -11.0, -6.0, -3.0, -2.0, -1.0, -1.0,
-4.0, -8.0, -22.0, -27.0, -32.0, -39.0, -46.0, -40.0, -46.0, -45.0,
-46.0, -49.0, -78.0, -95.0, -112.0, -125.0, -135.0, -145.0, -153.0,
-160.0, -168.0, -172.0, -172.0, -205.0, -205.0, -240.0, -220.0, -261.0,
-278.0, -278.0, -315.0, -309.0, -319.0, -316.0, -316.0, -314.0, -316.0,
-322.0, -327.0, -331.0, -334.0, -333.0, -323.0, -307.0, -280.0, -270.0,
-262.0, -253.0, -243.0, -233.0, -221.0, -215.0, -202.0, -202.0, -202.0,
-207.0, -214.0, -226.0, -238.0, -249.0, -249.0, -269.0, -284.0, -299.0,
-316.0, -333.0, -351.0, -372.0, -392.0, -408.0, -424.0, -436.0, -449.0,
-462.0, -478.0, -494.0, -518.0, -541.0, -557.0, -570.0, -579.0, -584.0,
-589.0, -592.0, -594.0, -594.0, -596.0, -598.0, -600.0, -599.0, -603.0,
-599.0, -595.0, -585.0, -574.0, -569.0, -562.0, -558.0, -545.0, -552.0,
-538.0, -521.0, -521.0, -514.0, -510.0, -503.0, -498.0, -495.0, -491.0,
-481.0, -475.0, -468.0, -463.0, -466.0, -470.0, -474.0, -480.0, -489.0,
-496.0, -510.0, -518.0, -524.0, -526.0, -526.0, -518.0, -505.0, -494.0,
-479.0, -454.0, -450.0, -447.0, -436.0, -426.0, -409.0, -389.0, -367.0,
-347.0, -326.0, -299.0, -289.0, -271.0, -253.0, -239.0, -224.0, -216.0,
-197.0, -184.0, -162.0, -141.0, -141.0, -129.0, -137.0, -130.0, -130.0,
-124.0, -124.0, -122.0, -122.0, -163.0, -163.0, -165.0, -159.0, -150.0,
-139.0, -122.0, -102.0, -82.0, -65.0, -51.0, -34.0, -13.0, -7.0, -1.0,
0.0, 3.0, 5.0, 6.0, 2.0, 6.0, 1.0, 1.0, 4.0, 1.0, 4.0, 4.0, 5.0, 8.0,
5.0, 4.0, 0.0, -2.0, -4.0, -8.0, -9.0, -19.0, -31.0, -37.0, -70.0,
-55.0, -94.0, -94.0, -166.0, -209.0, -260.0, -317.0, -373.0, -424.0,
-467.0, -501.0, -530.0, -548.0, -562.0, -556.0, -548.0, -538.0, -526.0,
-518.0, -511.0, -501.0, -493.0, -486.0, -480.0, -475.0, -471.0, -458.0,
-463.0, -444.0, -435.0, -444.0, -426.0, -407.0, -388.0, -379.0, -365.0,
-354.0, -346.0, -336.0, -330.0, -327.0, -324.0, -327.0, -337.0, -350.0,
-384.0, -384.0, -403.0, -424.0, -448.0, -469.0, -491.0, -500.0, -502.0,
-494.0, -455.0, -434.0, -412.0, -404.0, -397.0, -396.0, -392.0, -395.0,
-391.0, -389.0, -382.0, -376.0, -367.0, -355.0, -346.0, -332.0, -321.0,
-292.0, -304.0, -277.0, -277.0, -244.0, -226.0, -204.0, -186.0, -166.0,
-145.0, -125.0, -108.0, -90.0, -73.0, -53.0, -43.0, -29.0, -23.0, -16.0,
-10.0, -10.0, -10.0, -15.0, -21.0, -49.0, -72.0, -98.0, -128.0, -156.0,
-182.0, -198.0, -214.0, -227.0, -234.0, -242.0, -247.0, -249.0, -249.0,
-247.0, -241.0, -233.0, -223.0, -215.0, -208.0, -200.0, -196.0, -191.0,
-189.0, -187.0, -183.0, -181.0, -178.0, -181.0, -177.0, -170.0, -165.0,
-159.0, -153.0, -146.0, -137.0, -130.0, -122.0, -107.0, -107.0, -98.0,
-88.0, -88.0, -54.0, -42.0, -26.0, -12.0, 1.0, 14.0, 17.0, 19.0, 14.0,
3.0, -5.0, -18.0, -37.0, -51.0, -68.0, -79.0, -95.0, -138.0, -166.0,
-138.0, -196.0, -224.0, -253.0, -278.0, -300.0, -313.0, -327.0, -350.0,
-377.0, -402.0, -433.0, -454.0, -467.0, -476.0, -477.0, -478.0, -481.0,
-480.0, -479.0, -475.0, -470.0, -442.0, -464.0, -410.0, -393.0, -410.0,
-377.0, -356.0, -340.0, -321.0, -300.0, -280.0, -260.0, -244.0, -228.0,
-218.0, -210.0, -202.0, -197.0, -194.0, -189.0, -186.0, -181.0, -177.0,
-168.0, -163.0, -155.0, -149.0, -142.0, -137.0, -133.0, -126.0, -116.0,
-87.0, -103.0, -87.0,  -55.0, -40.0, -28.0, -20.0, -12.0, -8.0, -6.0,
-6.0, -8.0, -16.0, -27.0, -43.0, -61.0, -83.0, -106.0, -121.0, -135.0,
-151.0, -171.0, -199.0, -273.0, -273.0, -314.0, -354.0, -393.0, -437.0,
-478.0, -515.0, -545.0, -575.0, -598.0, -606.0, -604.0, -596.0, -580.0,
-564.0, -548.0, -532.0, -516.0, -507.0, -497.0, -476.0, -476.0, -476.0,
-442.0, -442.0, -429.0, -425.0, -415.0, -410.0, -405.0, -404.0, -407.0,
-403.0, -398.0, -403.0, -408.0, -418.0, -428.0, -437.0, -443.0, -438.0,
-430.0, -415.0, -399.0, -381.0, -354.0, -327.0, -296.0, -296.0, -229.0,
-194.0, -164.0, -138.0, -115.0, -97.0, -80.0, -65.0, -47.0, -37.0,
-27.0, -19.0, -15.0, -13.0, -12.0, -11.0, -13.0, -15.0, -22.0, -30.0,
-45.0, -57.0, -85.0, -95.0, -108.0, -116.0, -127.0, -138.0, -151.0,
-144.0, -150.0, -150.0, -146.0, -134.0, -134.0, -124.0, -108.0, -93.0,
-81.0, -63.0, -54.0, -52.0, -54.0, -55.0, -59.0, -69.0, -79.0, -93.0,
-112.0, -147.0, -130.0, -187.0, -187.0, -187.0, -229.0, -249.0, -249.0,
-299.0, -328.0, -354.0, -375.0, -395.0, -416.0, -434.0, -454.0, -484.0,
-494.0, -506.0, -506.0, -529.0, -540.0, -552.0, -555.0, -555.0, -553.0,
-548.0, -544.0, -532.0, -518.0, -499.0, -474.0, -446.0, -412.0, -374.0,
-336.0, -336.0, -249.0, -208.0, -166.0, -131.0, -103.0, -83.0, -68.0,
-55.0, -47.0, -40.0, -31.0, -22.0, -21.0, -16.0, -9.0, -12.0, -13.0,
-15.0, -18.0, -27.0, -30.0, -37.0, -56.0, -74.0, -90.0, -108.0, -128.0,
-146.0, -163.0, -175.0, -191.0, -197.0, -209.0, -218.0, -232.0, -227.0,
-230.0, -233.0, -231.0, -231.0, -233.0, -233.0, -230.0, -232.0, -237.0,
-246.0, -251.0, -245.0, -239.0, -242.0, -245.0, -248.0, -252.0, -259.0,
-276.0, -295.0, -320.0, -344.0, -365.0, -389.0, -422.0, -455.0, -493.0,
-532.0, -532.0, -551.0, -516.0, -471.0, -411.0, -355.0, -300.0, -244.0,
-191.0, -152.0, -118.0, -75.0, -75.0, -63.0, -57.0, -52.0, -51.0, -51.0,
-48.0, -46.0, -44.0, -41.0, -33.0, -33.0, -28.0, -28.0, -27.0, -27.0,
-28.0, -32.0, -38.0, -43.0, -49.0, -58.0, -58.0, -69.0, -82.0, -82.0,
-103.0, -103.0, -136.0, -146.0, -156.0, -162.0, -164.0, -158.0, -158.0,
-157.0, -154.0, -155.0, -154.0, -157.0, -154.0, -156.0, -156.0, -167.0,
-188.0, -209.0, -230.0, -252.0, -278.0, -304.0, -339.0, -379.0, -415.0,
-456.0, -491.0, -517.0, -531.0, -532.0, -530.0, -530.0, -511.0, -505.0,
-491.0, -474.0, -447.0])

x = xx[:,np.newaxis]
y = yy[:,np.newaxis]
z = zz[:,np.newaxis]

J = np.hstack((x*x,y*y,z*z,x*y,x*z,y*z, x, y, z))
K = np.ones_like(x) #column of ones
JT=J.transpose()
JTJ = np.dot(JT,J)
InvJTJ=np.linalg.inv(JTJ);
ABC = np.dot(InvJTJ, np.dot(JT,K))
vec=np.append(ABC,-1)

print(np.dot(JT,K))

# Das sind die 9 Koeffizienten der Ellipsoidengleichung:

[[ 3.65305490e+07]
 [ 3.40575891e+09]
 [ 9.84003130e+07]
 [ 8.19621600e+06]
 [ 6.06156000e+05]
 [ 4.78611628e+08]
 [-1.15100000e+03]
 [-1.83633100e+06]
 [-2.58085000e+05]]


In [8]:
# Jetzt geht es darum, daraus die Kalibrationsdaten zu filtern

Amat=np.array(
[
[ vec[0],     vec[3]/2.0, vec[4]/2.0, vec[6]/2.0 ],
[ vec[3]/2.0, vec[1],     vec[5]/2.0, vec[7]/2.0 ],
[ vec[4]/2.0, vec[5]/2.0, vec[2],     vec[8]/2.0 ],
[ vec[6]/2.0, vec[7]/2.0, vec[8]/2.0, vec[9]     ]
])
A3 = Amat[0:3,0:3]
A3inv = inv(A3)
ofs   = vec[6:9]/2.0
center = -np.dot(A3inv,ofs)
print('\nMitte des Ellipsoiden bei:',center)

# Center the ellipsoid at the origin
Tofs=np.eye(4)
Tofs[3,0:3]=center
print("\nTofs.T")
print(Tofs.T)

AmalTt = np.dot(Amat,Tofs.T)
print("\nAmalTt")
print(AmalTt)


Mitte des Ellipsoiden bei: [  -23.89778159 -1827.49415261  -306.32280167]

Tofs.T
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -2.38977816e+01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -1.82749415e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -3.06322802e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

AmalTt
[[-2.74898797e-07 -4.12082972e-10  1.33850401e-09 -8.47032947e-22]
 [-4.12082972e-10 -2.99921234e-07  1.00567366e-09 -1.01220437e-19]
 [ 1.33850401e-09  1.00567366e-09 -2.94491106e-07  0.00000000e+00]
 [-6.91253633e-06 -5.47806089e-04 -8.83394905e-05  2.83380194e-02]]


In [9]:
R = np.dot(Tofs,AmalTt)
R3=R[0:3,0:3]
R3test=R3/R3[0,0]
s1=-R[3, 3]
R3S=R3/s1
print('\nR3S \n',R3S)
(el,ec)=eig(R3S)
print("\nEigenwerte\n", el, "\n", ec)


R3S 
 [[ 9.70070607e-06  1.45416998e-08 -4.72335061e-08]
 [ 1.45416998e-08  1.05837049e-05 -3.54884952e-08]
 [-4.72335061e-08 -3.54884952e-08  1.03920850e-05]]

Eigenwerte
 [9.69732855e-06 1.03885186e-05 1.05906488e-05] 
 [[-0.99765064  0.06349897  0.02571142]
 [ 0.01367962 -0.18310228  0.98299869]
 [-0.06712722 -0.981041   -0.18180347]]


In [10]:
recip=1.0/np.abs(el)
axes=np.sqrt(recip)
print('\nDie Achsen sind\n', axes)

inve=inv(ec) #inverse is actually the transpose here
print('\nRotationsmatrix\n', inve)

# create transformation matrix
L = np.diag([1/axes[0],1/axes[1],1/axes[2]])
M=np.dot(inve.T,np.dot(L,inve))
print('\nTransformationsmatrix\n', M)


Die Achsen sind
 [321.12487257 310.25814304 307.28312972]

Rotationsmatrix
 [[-0.99765064  0.01367962 -0.06712722]
 [ 0.06349897 -0.18310228 -0.981041  ]
 [ 0.02571142  0.98299869 -0.18180347]]

Transformationsmatrix
 [[ 3.11458591e-03  2.27720790e-06 -7.45017111e-06]
 [ 2.27720790e-06  3.25325525e-03 -5.47660652e-06]
 [-7.45017111e-06 -5.47660652e-06  3.22366243e-03]]
